### ISSUE TITLE
Config file needs documentation 🧐

### ISSUE THREAD

**Issue by TGotwig** [RustScan/RustScan#136]
When running rustscan, one of the first messages is:

```
[~] The config file is expected to be at "/Users/tgotwig/Library/Application Support/rustscan/config.toml"
```

But when I search for `config` inside the readme I get nothing? 🤔

**Describe the solution you'd like**
Config file should be explained inside the readme. 🧐

**Comment by brandonskerritt** [comment]
Hey @TGotwig ! You've stumbled upon a mysterious new feature :wink: 

I was going to implement this, but then I got side tracked by #131 haha. 

The config file isn't implemented yet (see my unfinished PR at #126)

Since you tried to search for the config file, what was you expecting it to do? What would you like it to do? We're still working on this and community support is v/ welcomed :smile_cat: 

See issue #71 for more about config. In short at the moment it will be:

* A list of IP addresses to scan
* An adaptive learning based top X ports. So it _learns_ what ports you most frequently scans, and you can request top 1k ports, top 250 ports and so on. 

If you have any suggestions, please leave a comment. Since I finished the pretty interface I am working on this now :D

**Comment by TGotwig** [comment]
Oh nice so it's already work in progress 🙂

Not sure what to expect, just used it for a few minutes and thought this could be worth an issue 😁 maybe for overwriting default command-line-arguments like batch-size 🤓

**Comment by brandonskerritt** [comment]
Cool idea! I'll add this :technologist:
