### ISSUE TITLE
No IPv6 support

### ISSUE THREAD

**Issue by nutritiousreject** [RustScan/RustScan#15]
Makes me a very sad boy not being able to use ipv6

**Comment by brandonskerritt** [comment]
That also makes me a sad boy, what specifically doesn't work? Does it show any errors?

Theoretically, it does work with IPv6. :( Do you have an example address I can use to check? :)

**Comment by sciguy16** [comment]
I think the problem is that nmap wants a `-6` flag to enable IPv6 support

**Comment by brandonskerritt** [comment]
@sciguy16 You are probably right! I will see if the IpAddr data type will tell me whether it's IPv6, and will automatically pass it :)

**Comment by brandonskerritt** [comment]
SocketAddr is not IPv6 (at least in our code), I will work on fixing that into IPv6 :)

**Comment by sciguy16** [comment]
Yeah it's this line that's causing the problems:
https://github.com/brandonskerritt/RustScan/blob/6906177ec282c55232d4ee4d0d9eb1ebdcba6ca0/src/scanner.rs#L64

If you store the IP in `Scanner` as an `IpAddr` rather than a `String` then you can use [SocketAddr::new](https://doc.rust-lang.org/nightly/std/net/enum.SocketAddr.html#method.new) to build the socketaddr from the host-port combination. There should be a slight performance increase from that too, as you'd be getting rid of a string allocation and the IP parsing stage.

**Comment by brandonskerritt** [comment]
This is implemented in master! Will release in 1.4 :)
