### ISSUE TITLE
Command no longer works

### ISSUE THREAD

**Issue by islanddog** [RustScan/RustScan#308]
**Describe the bug**
NMAP commands that ran last update after the rustscan completed no longer work.

**To Reproduce**
`rustscan -u 5000 -a IPADDRESS -- -A -sC -sV --script 'default,vuln' -oX scan`

**Expected behavior**
Normally it would kick off the NMAP scan, now it says
```
[~] Starting Script(s)
[>] Script to be run Some("nmap -vvv -p {{port}} {{ip}}")
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kali
 - Browser Firefox
 - Version 78.3.0esr (64-bit)

**Additional context**
Was the scheme for the formatting changed as I had a script setup and working less then a week ago before the update.

**Comment by bergabman** [comment]
The execution format what you see there is just the basic format that gets used, the embedded nmap script options. When a script gets loaded, the stored execution format gets shown. But the extra arguments still get added to the nmap script (and all the srcipts that get run). I tried your commandline options and it was running fine for me. It took almost a minute despite I was running it on `127.0.0.1` because a lot of script can get loaded with the `'default,vuln'` nmap flags. I can also see in the nmap output file that nmap is running. 

![image](https://user-images.githubusercontent.com/44554109/98470587-f87bf500-21e6-11eb-8aa9-f4a2077c8831.png)


I have to admit there is no feedback in RustScan while a long running script is running, and we have to improve that! But the arguments you gave should work with the latest release and I can not reproduce the bug. You can try to run the scan with less added arguments to see if there is some error maybe. If you still face the problem please run the scanner with `RUST_LOG=debug` to get some more information from the run. There you can also see what final arguments get passed to nmap.

![image](https://user-images.githubusercontent.com/44554109/98470602-18131d80-21e7-11eb-8626-6f8559c11c42.png)

**Comment by islanddog** [comment]
Thanks for the quick response. When I ran the command and saw a different response I thought the response was a notification of a syntax error. Normally I would see an NMAP trigger within 30sec or so and left it running for over a minute. As in most cases it's minimal open ports so it sufficed for the purpose. I will try and openly leave the scan running to see an end result.

Apologies for lack of patience.

**Comment by bee-san** [comment]
Are you saying that the Nmap script is slower than usual? That's something we can investigate 🤔

**Comment by bergabman** [comment]
No need to apologize, I understand why you wrote. The behavior changed and the output seem to takes more time. I don't think anything runs slower, just the feedback from the script is different. 

The original implementation was using `std` defined command execution, and in the current version we are using a little more enhanced library to execute the scripts. I will check if we can pipe stdout of the scripts to the terminal output while it's running, to get instant updates. An instant feedback is always better.

**Comment by islanddog** [comment]
> 
> 
> No need to apologize, I understand why you wrote. The behavior changed and the output seem to takes more time. I don't think anything runs slower, just the feedback from the script is different.
> 
> The original implementation was using `std` defined command execution, and in the current version we are using a little more enhanced library to execute the scripts. I will check if we can pipe stdout of the scripts to the terminal output while it's running, to get instant updates. An instant feedback is always better.

Thanks and exactly right. I tried again and it seems like the behavior now when rustscan interacts with NMAP provides no context or information until complete. Upon NMAP finishing it displayed the entire output which in previous versions it showed as it was ongoing. I do agree that instant feedback is amazing but at least now I know. Thanks for the help.
