### ISSUE TITLE
Rustscan - Docker - You requested a scan type which requires root privileges. QUITTING!

### ISSUE THREAD

**Issue by Green360** [RustScan/RustScan#414]
I am trying to use the Rustscan (2.0.1) in Parrot OS 4.11 via Docker.
For certain scan modes ones needs to have root privileges.
Unfortunately, I just cant get it to work.
I am not so experienced and hope that someone can point me into the right direction.

Example:
`$ docker run -it --rm --name rustscan rustscan/rustscan:2.0.1 -b 20000 -t 2000 -a 1.2.3.4 -- -sS`

Output:
```...
[~] Starting Script(s) 
[>] Script to be run Some("nmap -vvv -p {{port}} {{ip}}") 
You requested a scan type which requires root Privileges. 
QUITTING! 
[!] Error Exit code = 1
```

I obviously tried it with sudo but still the same result. What am I missing?
`$ sudo docker run -it --rm --name rustscan rustscan/rustscan:2.0.1 -b 20000 -t 2000 -a 1.2.3.4 -- -sS`

**Comment by xrzhev** [comment]
This is because the executable user in the rustscan/rustscan:2.0.1 container is running as the `rustscan` user, not as `root`.
[Reference:](https://hub.docker.com/layers/rustscan/rustscan/2.0.1/images/sha256-77b3823022123aaf80d21c7e506c8f24bc24342fcdb77cc946d2c79a22398d39?context=explore)

If you want to make the executable user of the rustscan container root, try the following command.
`sudo docker run -it --rm --name rustscan --user=root:root rustscan/rustscan:2.0.1 -b 20000 -t 2000 -a 1.2.3.4 -- -sS`

**Comment by Green360** [comment]
Thank you! It works.
