### ISSUE TITLE
List of IP Addresses from a file

### ISSUE THREAD

**Issue by derrickberg-dev** [RustScan/RustScan#452]
**Is your feature request related to a problem? Please describe.**
I would like to use RustScan to port scan a list of IP addresses but it doesn't seem right to have to put 100 IP addresses in the command line.

**Describe the solution you'd like**
The ability to provide a file as input.

**Describe alternatives you've considered**
Pasting a long list of comma separated IP addresses

**Comment by gangov** [comment]
hey @derrickberg-dev 

I thought of implementing this one, but it turns out that the cli already supports this; all it takes is the -a OPTION followed by the path to the file containing all the IP addresses; on my machine, after building it's the following:

./rustscan -a ../../ips.txt 

note the ../../  - that is because I executed from the target/release folder and had to go up 

P.S.: Also the list of comma-separated IP addresses works with the -a OPTION (./rustscan -a 172.217.20.78,40.114.177.156)

@bee-san I guess we can close this one
