### ISSUE TITLE
Request for Automated Docker Image Builds via GitHub Actions: No Update for 2 Years

### ISSUE THREAD

**Issue by cfbsks** [RustScan/RustScan#502]
It appears that the GitHub issue is requesting for an automatic build of a Docker image through GitHub Actions (GHA), but there has been no update or progress for the past two years. It may be necessary to follow up with the repository owner or maintainers to inquire about the status of the issue and whether it is still being actively worked on.

**Comment by cfouche3005** [comment]
Futhermore, the recomended usage is docker which, the container, is outdated

**Comment by bee-san** [comment]
The docker CI appears to be broken:
https://github.com/RustScan/RustScan/pull/472

**Comment by CMNatic** [comment]
I can take a look into this. The problem is that the current process of automatic tagging of builds now requires a subscription DockerHub @bee-san. I could just push some new releases as tags.

I think we could use a GitHub action instead? https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

**Comment by bee-san** [comment]
@CMNatic  This PR is meant to add CI for it https://github.com/RustScan/RustScan/pull/472 but it does not work :( 

Whatd'ya think about switching to GitHub images (or packages? whatever they're calling it) 🤔  I have only ever used Dockerhub!
