### ISSUE TITLE
Invalid link to docker installation guide in wiki

### ISSUE THREAD

**Issue by ssupdoc** [RustScan/RustScan#503]
**Describe the bug**
The wiki section for Docker installation on top of the Installation Guide has a wrong link and redirects to the RustScan Installation Guide. Note: The link in the Docker section down below is fine though.

**To Reproduce**
1. Go to [Installation Guide -> Docker](https://github.com/RustScan/RustScan/wiki/Installation-Guide#docker-)
2. Click on 'follow their guide' link.
3. Observe it takes you back to the same page.

**Expected behavior**
It is supposed to take you to https://docs.docker.com/engine/install/ as in [the second Docker section](https://github.com/RustScan/RustScan/wiki/Installation-Guide#docker-whale).

**Comment by EdTheLegendary** [comment]
I found the problem: the link was absent. I added the link and now it works. Here is a link to my fork of the wiki: https://github.com/EdTheLegendary/RustScan.wiki.git

**Comment by EdTheLegendary** [comment]
P.S. If you test my fix and it doesn't work, it is likely because you clicked the section on installing RustScan within my wiki. When you do that it redirects to the original erroneous page because that page is hardcoded in the wiki home page. Here is a link to my working page: https://github.com/EdTheLegendary/RustScan/wiki/Installation-Guide

**Comment by Wolf-06** [comment]
Is this the issue still open ?

**Comment by CMNatic** [comment]
Hey thank you. I've updated the wiki to point the first "To install Docker, follow their guide" to https://docs.docker.com/engine/install/.

Apologies for the delay on this ticket
