### ISSUE TITLE
Quiet version does not work on docker version

### ISSUE THREAD

**Issue by Bozx** [RustScan/RustScan#508]
It says there is no such flag.
Regards

**Comment by millette** [comment]
Duplicate, see #514

**Comment by bee-san** [comment]
Hi there 👋🏻 

As of November 2024 the RustScan team has decided to remove all support for officially maintaining packages other than `Cargo`.

**Why?**

We are an incredibly small team and we found we were working more on fixing packages / the CI for packages rather than making RustScan a great tool.

**How will I use RustScan?**

RustScan is in many, many package managers already:
https://repology.org/project/rustscan/versions 

As well as on others like Snap https://snapcraft.io/rustscan or Docker https://hub.docker.com/search?q=rustscan and we may even be built into some pentesting distros by default.

If your favourite repo does not have a RustScan package, you are free to either make one or request one from them. RustScan is quite popular with thousands of GitHub stars and downloads, and it is incredibly easy to build (git clone && cargo build). We are sure that if we are not already distributed some way, it should not be hard to make a package.

**What about Cargo?**

Cargo will be our only officially supported package, as it's built into Rust by default and it's what our developers use.

If you want to use it, please install Rust and then run `cargo install rustscan`.
