### ISSUE TITLE
Add stable tag to docker

### ISSUE THREAD

**Issue by Darks1de42** [RustScan/RustScan#533]
**Is your feature request related to a problem? Please describe.**
In the manual stands there is the Tag `alpine`, but this does not exist.

**Describe the solution you'd like**
The use of the stable Tag for the latest stable version would be nice. Then you can use an alias which uses always the latest version.

**Comment by CMNatic** [comment]
Ahh that's interesting. I'll publish the `alpine` tag. The repo has the `latest` tag, which should be considered the stable release. However, there's a problem with the CI/CD pipeline in pushing the actual latest stable release to the repo. This is also on my todo.

Thanks :)

**Comment by bee-san** [comment]
Hi there 👋🏻 

As of November 2024 the RustScan team has decided to remove all support for officially maintaining packages other than `Cargo`.

**Why?**

We are an incredibly small team and we found we were working more on fixing packages / the CI for packages rather than making RustScan a great tool.

**How will I use RustScan?**

RustScan is in many, many package managers already:
https://repology.org/project/rustscan/versions 

As well as on others like Snap https://snapcraft.io/rustscan or Docker https://hub.docker.com/search?q=rustscan and we may even be built into some pentesting distros by default.

If your favourite repo does not have a RustScan package, you are free to either make one or request one from them. RustScan is quite popular with thousands of GitHub stars and downloads, and it is incredibly easy to build (git clone && cargo build). We are sure that if we are not already distributed some way, it should not be hard to make a package.

**What about Cargo?**

Cargo will be our only officially supported package, as it's built into Rust by default and it's what our developers use.

If you want to use it, please install Rust and then run `cargo install rustscan`.
