### ISSUE TITLE
Could you please make an Arm Debian package?

### ISSUE THREAD

**Issue by gtasb** [RustScan/RustScan#579]
With some reason, i can`t run docker on my machine, can you make an arm debian package?

**Comment by PsypherPunk** [comment]
@gtasb, there are some fun differences between [Debian](https://www.debian.org/ports/) and [Rust](https://doc.rust-lang.org/nightly/rustc/platform-support.html) re. architecture: do you know if Rust's `aarch64-unknown-linux-gnu` works okay on your machine? 

If so, this should be straightforward enough.

**Comment by gtasb** [comment]
> @gtasb, there are some fun differences between [Debian](https://www.debian.org/ports/) and [Rust](https://doc.rust-lang.org/nightly/rustc/platform-support.html) re. architecture: do you know if Rust's works okay on your machine?`aarch64-unknown-linux-gnu`
> 
> If so, this should be straightforward enough.

yes

**Comment by PsypherPunk** [comment]
FYI, I did start looking at this:

1. adding the appropriate `build` to the `matrix` and setting `cross: true` works perfectly!
2. …but then the Python tests fail for that step only.
3. it looks like `actions-rs/toolchain` is [now deprecated](https://github.com/actions-rs/toolchain/issues/216) and equally, it's not clear what the de facto standard Action might be.

So the build isn't too tricky but getting it working in a pipeline is proving a little more rabbit-hole-y than expected.

**Comment by AD2011** [comment]
It's available for arch linux: [here](https://archlinuxarm.org/packages/aarch64/rustscan). But it would be more proper if the devs release binary for arm linux on the releases page

**Comment by bee-san** [comment]
Hi there 👋🏻 

As of November 2024 the RustScan team has decided to remove all support for officially maintaining packages other than `Cargo`.

**Why?**

We are an incredibly small team and we found we were working more on fixing packages / the CI for packages rather than making RustScan a great tool.

**How will I use RustScan?**

RustScan is in many, many package managers already:
https://repology.org/project/rustscan/versions 

As well as on others like Snap https://snapcraft.io/rustscan or Docker https://hub.docker.com/search?q=rustscan and we may even be built into some pentesting distros by default.

If your favourite repo does not have a RustScan package, you are free to either make one or request one from them. RustScan is quite popular with thousands of GitHub stars and downloads, and it is incredibly easy to build (git clone && cargo build). We are sure that if we are not already distributed some way, it should not be hard to make a package.

**What about Cargo?**

Cargo will be our only officially supported package, as it's built into Rust by default and it's what our developers use.

If you want to use it, please install Rust and then run `cargo install rustscan`.
