### ISSUE TITLE
Using a parenthesis in script scan flag causes a crash in Nmap

### ISSUE THREAD

**Issue by henryreed** [RustScan/RustScan#62]
Hello. 

I am attempting to run RustScan against a lab machine using my favorite set of Nmap flags, which includes `--script "(vuln and safe) or default"`; however, this appears to fail if I do it through RustScan, potentially because RustScan misinterprets the parenthesis. See the screenshots below:
## Nmap scan without RustScan:
![image](https://user-images.githubusercontent.com/60915078/88450414-964bdf80-ce03-11ea-9ab0-ffd80fe8de53.png)

## RustScan on the same box with the same flags
![image](https://user-images.githubusercontent.com/60915078/88450535-95677d80-ce04-11ea-8de7-e7f82ff587bf.png)

Running this in Kali Linux 2020.3. Please let me know if you have any questions.

**Comment by brandonskerritt** [comment]
This is because the quotations are deleted from the string. 

Running 

```
./target/release/rustscan 127.0.0.1 -- --script "(vuln and safe)"
```

Results in the Nmap scan:

```
nmap --script (vuln and safe) -Pn -vvv -p 53,631,59946 127.0.0.1
```

By escaping the quotations, we get:

```
nmap --script "(vuln and safe)" -Pn -vvv -p 53,631,40732,46624 127.0.0.1
```

But we get the error:

```
'"(vuln' did not match a category, filename, or directory
stack traceback:
```

But if we run this command in terminal, it works:

```
➜ nmap '(vuln and safe)' -Pn -vvv -p 53,631,40732,46624 127.0.0.1
Starting Nmap 7.80 ( https://nmap.org ) at 2020-07-25 10:19 BST
```

How strange!

**Comment by bernardoamc** [comment]
I've managed to replicate and pinpoint where the issue is happening, the fix is not straightforward though. 

**Problem:**

We are splitting the argument string by white-space. This works well for our simple flags, but `'(vuln and safe)'`  shouldn't be split.

We need to generate an ` args` vector similar to: 

`["--script", "(vuln and safe) or default", "-Pn", "-vvv",  "-p", "22,80,139,445", "xx.xx.xxx.xxx"]`

What we are getting instead is:

```
[
    "--script",
    "(vuln",
    "and",
    "safe)",
    "or",
    "default",
    "-Pn",
    "-vvv",
    "-p",
    "22,80,139,445",
    "xx.xx.xxx.xxx",
]

```

**Comment by brandonskerritt** [comment]
Could we check the arguments provided for quotation marks or brackets, and then:
```
args = []
if brackets or quotation marks
    while not char = bracket or quotation:
          args.append(char)
```

Kind of bad psuedocode since theirs bugs in it, but if we built a while loop that looped through char by char (when it sees white space and its not in SKIP mode, mark the previous chars as a single word). If it sees a " or (, it "skips" this and uses the "append to list as a string" function from the previous sentence until it finds the matching bracket or quotation, at which point it goes back to normal mode.

This is quite a famous problem in computer science, I studied it once! Finding matching socks but the order matters. I'm sure there's some fancy regex way or graph theory way to do this, but this is just my first thought :)

**Comment by bernardoamc** [comment]
We can solve it for sure, but that's half the problem. Parsing arguments is way harder due to the complex specification from OSs.

Ideally we should use something like [shellwords](https://github.com/tmiasko/shell-words) to take care of these edge cases. I never used this lib though, so we can research alternatives. :) 

What do you think?
