### ISSUE TITLE
Feature Request: Docker image for arm64

### ISSUE THREAD

**Issue by mfrancisbeehive** [RustScan/RustScan#645]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
 I would like to see a docker image for arm64. Currently I have built one myself, but being able to pull it would be nice. 

**Describe alternatives you've considered**
I've built one myself using your Dockerfile on my own computer for now. 

**Additional context**
Building for multiple architectures is pretty easy. Just run `docker build --platform linux/amd64,linux/arm64 -t rustscan/rustscan .`

**Comment by lazyzyf** [comment]
it will be helpful if the author can release the arm64 platform docker image, so users don't need to build themselves.

**Comment by mcamou** [comment]
I would like to tackle this as part of Hacktoberfest. Could you please assign me and add the `hacktoberfest-accepted` label?

**Comment by lazyzyf** [comment]
thanks, @mcamou  for your help. I don't know how to assign you and add the label, can you or anyone else to do it for me?

**Comment by mcamou** [comment]
Hey @lazyzyf, only repo admins can do that (assign and label). If you're an admin, it's all done on this same page (the page of the PR), on the right-hand column.

To assign: Click on "Assignees", search for `mcamou` and select to enable the check.

To set labels: Click on "Labels", search for `hacktoberfest` and click on `hacktoberfest-approved`. If you only see `hacktoberfest`, I *believe* it should work too.

**Comment by mcamou** [comment]
Perhaps @PsypherPunk can do this? I can't see who the maintainers are, just going by the commit history.

**Comment by PsypherPunk** [comment]
Hey, @mcamou: label and and issue assigned.

I will caveat this with that, although RustScan previously participated

**Comment by PsypherPunk** [comment]
Apologies for the close/open: never GitHub on mobile.

**Comment by mcamou** [comment]
Thanks @PsypherPunk. PR here: https://github.com/RustScan/RustScan/pull/675.

**Comment by lazyzyf** [comment]
I would say only if the arm64 image released on hub.docker.com can deem this issue as completd.

**Comment by PsypherPunk** [comment]
A fair comment: this was an auto-close courtesy of GitHub.

**Comment by bee-san** [comment]
[
Hi there 👋🏻 

As of November 2024 the RustScan team has decided to remove all support for officially maintaining packages other than `Cargo`.

**Why?**

We are an incredibly small team and we found we were working more on fixing packages / the CI for packages rather than making RustScan a great tool.

**How will I use RustScan?**

RustScan is in many, many package managers already:
https://repology.org/project/rustscan/versions 

As well as on others like Snap https://snapcraft.io/rustscan or Docker https://hub.docker.com/search?q=rustscan and we may even be built into some pentesting distros by default.

If your favourite repo does not have a RustScan package, you are free to either make one or request one from them. RustScan is quite popular with thousands of GitHub stars and downloads, and it is incredibly easy to build (git clone && cargo build). We are sure that if we are not already distributed some way, it should not be hard to make a package.

**What about Cargo?**

Cargo will be our only officially supported package, as it's built into Rust by default and it's what our developers use.

If you want to use it, please install Rust and then run `cargo install rustscan`.](url)
