### ISSUE TITLE
UDP scan returns all ports as open

### ISSUE THREAD

**Issue by eirnym** [RustScan/RustScan#663]
**Describe the bug**

1. TCP Scan shows the same results as nmap.
2. UDP scan returns all ports as open on scanning a typical Windows host. 
3. minor issue (may be expected): two coloured vertical lines in RustScan banner as shown below.

**To Reproduce**
1. no configuration files supplied to any of the program.
2. RustScan installed using cargo (`cargo install rustscan`)
4. NMap installed using MacPorts
5. The only configuration I have on Windows Firewall is to allow port 22 and disallow any other.
6. `rustscan -a <IP> --ulimit 5000 -r 1-65535 --udp --scripts none`
7. `nmap -n -p1-65535 -sU -PN <IP> -P0`

**Expected behavior**

NMap shows that system accepts, but doesn't reply to any UDP packet
RustScan should do the same

**Screenshots**

<img width="726" alt="Zrzut ekranu 2024-09-29 o 13 49 48" src="https://github.com/user-attachments/assets/41515f9e-f987-4843-b72f-ac5e6e2cf5aa">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: not aplicable
 - Version 2.3.0
 - Terminal: macOS default terminal.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by x64dot** [comment]
Could it possibly be a IPS/IDS causing the false positives?

**Comment by bee-san** [comment]
This ticket has been inactive for a while, closing.

**Comment by eirnym** [comment]
@bee-san im waiting bug to be fixed. Please reopen the ticket

**Comment by fabianbees** [comment]
Hi, i can also reproduce this issue still with the latest version.

I provided the fix with PR #737 .

The cause for this issue can be found here: https://github.com/RustScan/RustScan/blob/master/src/scanner/mod.rs#L196

- In this line we should not return Ok(socket), because we reach this point only when all tries have timed-out.
- Instead we should return an Err, so we do not consider a timed-out socket as open.
