### ISSUE TITLE
My scan req root priv, when i already on root priv

### ISSUE THREAD

**Issue by ImJoke** [RustScan/RustScan#672]
**Describe the bug**
This is so weird, cuz i already scanning with sudo priv, but the error message said i didn't

**To Reproduce**
1. Using rustscan docker version
2. Scan like normal

**Expected behavior**
Return result without error

**Screenshots**
![image](https://github.com/user-attachments/assets/3371ff46-5ce5-4cce-a298-1d061228fb57)

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Browser [e.g. chrome, safari] : Firefox
 - Version [e.g. 22] : Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux

**Comment by PsypherPunk** [comment]
When you say you're using the "rustscan docker version", has `rustscan` been aliased? So that's actually a `docker run`?

If that's the case, I _think_ the resulting Nmap will run inside the container as the [`rustscan`](https://github.com/RustScan/RustScan/blob/master/Dockerfile#L17) user, not `root`.

If you could confirm that above, this might be a limitation of the way we build the Docker container at the moment.

**Comment by bee-san** [comment]
Hi there 👋🏻 

As of November 2024 the RustScan team has decided to remove all support for officially maintaining packages other than `Cargo`.

**Why?**

We are an incredibly small team and we found we were working more on fixing packages / the CI for packages rather than making RustScan a great tool.

**How will I use RustScan?**

RustScan is in many, many package managers already:
https://repology.org/project/rustscan/versions 

As well as on others like Snap https://snapcraft.io/rustscan or Docker https://hub.docker.com/search?q=rustscan and we may even be built into some pentesting distros by default.

If your favourite repo does not have a RustScan package, you are free to either make one or request one from them. RustScan is quite popular with thousands of GitHub stars and downloads, and it is incredibly easy to build (git clone && cargo build). We are sure that if we are not already distributed some way, it should not be hard to make a package.

**What about Cargo?**

Cargo will be our only officially supported package, as it's built into Rust by default and it's what our developers use.

If you want to use it, please install Rust and then run `cargo install rustscan`.
