### ISSUE TITLE
Custom Python Modules

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#80]
# Problem
Some people want to write exploit modules with RustScanner
But I don't, as RustScanner is for improving Nmap.

# Solution
A custom exploit module system written in Python.
So we already have the IP's and port numbers to pass into Nmap.

What if, instead of passing straight to Nmap, we check to see if a module exists (either via arguments) or if a Rust module exists.
If it does, run the exploits in that module against the ports / IP addresses.

We should focus on 2 things:
- [ ] The exploits module will allow Python to be used. It is really important that people can code exploits in a simple to use language
- [ ] We focus more on the modularity of RustScanner, rather than the exploits. We should move from a _tool_ to an enabler for an ecosystem.

**Comment by TrilogyTrustGlbfund** [comment]
###Trustful do Lynch###

**Comment by smackhack** [comment]
Ideally, since RustScan's functionality is mainly retrieving open ports, it wouldn't have to be a very complicated API, I would think that just running any scripts set by the user to run per-port or post-scan should be executed prior to sending it off to nmap, and maybe even a flag optional to not output to nmap at all.

Ideally, I think just making RustScanner the fastest and most efficient port scanner would be useful enough, and allow other people to create what they want to do with the output of list of open ports.

**Comment by Nexus2k** [comment]
Have a look at https://github.com/google/tsunami-security-scanner which provides the mentioned scripting engine to pass open ports to exploit modules.

**Comment by subfission** [comment]
What about a few options:
1. Could this be passed over a network socket or domain socket perhaps?  
eg. `echo '{"port":80, "host":"192.168.1.1"}'` >> `127.0.0.1:21212` or `/tmp/rustscan.sock` 

2. Call a defined shell script `rustscan --script /opt/pokeportmore 192.168.1.1`

This would allow us to use whatever language/tool and get creative with shell scripts.
